# Generated by Django 5.1 on 2024-09-08 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='influencer',
            name='average_likes',
        ),
        migrations.RemoveField(
            model_name='influencer',
            name='average_views',
        ),
        migrations.RemoveField(
            model_name='influencer',
            name='created_date',
        ),
        migrations.RemoveField(
            model_name='influencer',
            name='recent_three_videos',
        ),
        migrations.RemoveField(
            model_name='influencer',
            name='subscriber_count',
        ),
        migrations.RemoveField(
            model_name='influencer',
            name='top_video',
        ),
        migrations.RemoveField(
            model_name='influencer',
            name='video_count',
        ),
        migrations.RemoveField(
            model_name='influencer',
            name='view_count',
        ),
    ]
