# Generated by Django 5.1 on 2024-08-28 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_brand',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_influencer',
        ),
    ]
