# Generated by Django 5.1 on 2024-08-29 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_user_is_brand_remove_user_is_influencer'),
    ]

    operations = [
        migrations.AddField(
            model_name='influencer',
            name='instagram_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
