# Generated by Django 5.1 on 2024-08-30 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_influencer_instagram_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='influencer',
            name='average_likes',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='influencer',
            name='average_views',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='influencer',
            name='recent_three_videos',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='influencer',
            name='subscriber_count',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='influencer',
            name='top_video',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='influencer',
            name='video_count',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='influencer',
            name='view_count',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='influencer',
            name='youtube_id',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
