# Generated by Django 5.1 on 2024-08-29 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youtube_apis', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='YouTubeCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_id', models.CharField(max_length=50, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
