# Generated by Django 5.1 on 2024-09-04 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youtube_apis', '0002_youtubecategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='youtubechannel',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='youtubechannel',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='youtubechannel',
            name='channel_id',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='youtubechannel',
            name='subscriber_count',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='youtubechannel',
            name='video_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='youtubechannel',
            name='view_count',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='youtubevideo',
            name='comment_count',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='youtubevideo',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='youtubevideo',
            name='like_count',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='youtubevideo',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='youtubevideo',
            name='video_id',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='youtubevideo',
            name='view_count',
            field=models.BigIntegerField(default=0),
        ),
    ]
