# Generated by Django 5.1 on 2024-09-04 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('youtube_apis', '0003_youtubechannel_description_youtubechannel_title_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='youtubechannel',
            name='description',
        ),
        migrations.RemoveField(
            model_name='youtubechannel',
            name='title',
        ),
    ]
